AWSTemplateFormatVersion:
  "2010-09-09"
Description: VPC & Network construction

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------#
Parameters:
  ProjectName:
    Type: String
    Default: eks-practice
  K8sClusterName:
    Type: String
    Default: eks-practice-cluster
  Stage:
    Type: String
    Default: dev

Resources:
  # ------------------------------------------------------------#
  #  VPC
  # ------------------------------------------------------------#
  # VPC Create
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/16"
      # VPC に対して DNS 解決がサポートされているか
      EnableDnsSupport: "true"
      # VPC 内に起動されるインスタンスが DNS ホスト名を取得するか
      EnableDnsHostnames: "true"
      # VPC 内に起動されるインスタンスの許可されているテナンシー
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-vpc"

  # InternetGateway Create
  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-igw"

  # IGW Attach
  InternetGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # ------------------------------------------------------------#
  #  Subnet
  # ------------------------------------------------------------#
  # Public1 Subnet Create
  Public1Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: "10.0.0.0/24"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-public1-subnet"
        - Key: kubernetes.io/role/elb
          Value: "1"
        - Key: !Sub "kubernetes.io/cluster/${K8sClusterName}"
          Value: "shared"

  # Public2 Subnet Create
  Public2Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: "10.0.1.0/24"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-public2-subnet"
        - Key: kubernetes.io/role/elb
          Value: "1"
        - Key: !Sub "kubernetes.io/cluster/${K8sClusterName}"
          Value: "shared"

  # Public3 Subnet Create
  Public3Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1d"
      CidrBlock: "10.0.2.0/24"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-public3-subnet"
        - Key: kubernetes.io/role/elb
          Value: "1"
        - Key: !Sub "kubernetes.io/cluster/${K8sClusterName}"
          Value: "shared"

  # Private1 Subnet Create
  Private1Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1a"
      CidrBlock: "10.0.10.0/24"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-private1-subnet"
        - Key: ForK8SPrivateCluster
          Value: "true"
        - Key: kubernetes.io/role/internal-elb
          Value: "1"
        - Key: !Sub "kubernetes.io/cluster/${K8sClusterName}"
          Value: "shared"

  # Private2 Subnet Create
  Private2Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1c"
      CidrBlock: "10.0.11.0/24"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-private2-subnet"
        - Key: ForK8SPrivateCluster
          Value: "true"
        - Key: kubernetes.io/role/internal-elb
          Value: "1"
        - Key: !Sub "kubernetes.io/cluster/${K8sClusterName}"
          Value: "shared"

  # Private3 Subnet Create
  Private3Subnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: "ap-northeast-1d"
      CidrBlock: "10.0.12.0/24"
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-private3-subnet"
        - Key: ForK8SPrivateCluster
          Value: "true"
        - Key: kubernetes.io/role/internal-elb
          Value: "1"
        - Key: !Sub "kubernetes.io/cluster/${K8sClusterName}"
          Value: "shared"

  # ------------------------------------------------------------#
  #  RouteTable
  # ------------------------------------------------------------#
  # Public RouteTable Create
  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-public-route"

  # Private RouteTable Create
  PrivateRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-network-private-route"

  # ------------------------------------------------------------#
  # Routing
  # ------------------------------------------------------------#
  # Public Route Create
  PublicRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway

  # ------------------------------------------------------------#
  # RouteTable Associate
  # ------------------------------------------------------------#
  # Public1RouteTable Associate PublicSubnet
  Public1SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref Public1Subnet
      RouteTableId: !Ref PublicRouteTable
  Public2SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref Public2Subnet
      RouteTableId: !Ref PublicRouteTable
  Public3SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref Public3Subnet
      RouteTableId: !Ref PublicRouteTable

  Private1SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref Private1Subnet
      RouteTableId: !Ref PrivateRouteTable
  Private2SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref Private2Subnet
      RouteTableId: !Ref PrivateRouteTable
  Private3SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !Ref Private3Subnet
      RouteTableId: !Ref PrivateRouteTable

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#
Outputs:
  # VPC
  VPC:
    Value: !Ref VPC
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-vpc"

  # Subnet
  Public1Subnet:
    Value: !Ref Public1Subnet
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-public1-subnet"

  Public2Subnet:
    Value: !Ref Public2Subnet
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-public2-subnet"

  Public3Subnet:
    Value: !Ref Public3Subnet
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-public3-subnet"

  Private1Subnet:
    Value: !Ref Private1Subnet
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-private1-subnet"

  Private2Subnet:
    Value: !Ref Private2Subnet
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-private2-subnet"

  Private3Subnet:
    Value: !Ref Private3Subnet
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-private3-subnet"

  VPCCidrBlock:
    Value: !GetAtt VPC.CidrBlock
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-vpc-cidrblock"

  InternetGateway:
    Value: !Ref InternetGateway
    Export:
      Name: !Sub "${ProjectName}-${Stage}-network-igw"

  PrivateRouteTable:
    Value: !Ref PrivateRouteTable
    Export:
      Name: !Sub "${ProjectName}-${Stage}-private-route-table"
