AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Endpoint'

Parameters:
  ProjectName:
    Type: String
    Default: eks-practice
  Stage:
    Type: String
    Default: dev

# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +
Resources:
# + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + + +

  # ------------------------------------------------------------#
  # Create ECR dkr End Point
  # ------------------------------------------------------------#
  EcrDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .ecr.dkr
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-private1-subnet
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-private2-subnet
      VpcId:
        Fn::ImportValue:
          !Sub ${ProjectName}-${Stage}-network-vpc
      VpcEndpointType: Interface
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-sg-api-vpc-endpoint
      PrivateDnsEnabled: true

  # ------------------------------------------------------------#
  # Create ECR Api End Point
  # ------------------------------------------------------------#
  EcrApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .ecr.api
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-private1-subnet
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-private2-subnet
      VpcId:
        Fn::ImportValue:
          !Sub ${ProjectName}-${Stage}-network-vpc
      VpcEndpointType: Interface
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-sg-api-vpc-endpoint
      PrivateDnsEnabled: true

  # ------------------------------------------------------------#
  # Create Logs End Point
  # ------------------------------------------------------------#
  LogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Join
        - ''
        - - com.amazonaws.
          - !Ref 'AWS::Region'
          - .logs
      SubnetIds:
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-private1-subnet
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-network-private2-subnet
      VpcId:
        Fn::ImportValue:
          !Sub ${ProjectName}-${Stage}-network-vpc
      VpcEndpointType: Interface
      SecurityGroupIds:
        - Fn::ImportValue:
            !Sub ${ProjectName}-${Stage}-sg-api-vpc-endpoint
      PrivateDnsEnabled: true
