version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
  parameter-store:
    DOCKERHUB_USERNAME: /CI/DOCKERHUB_USERNAME
    DOCKERHUB_PASSWORD: /CI/DOCKERHUB_PASSWORD

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - DEFAULT=`pwd`
      - echo `java --version`

      - echo login Docker Hub
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - echo login ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo build sample-application
      - ./gradlew sample-application:build

      - echo build sample-application Docker image
      - cd ./sample-application
      - docker image build -t $IMAGE_REPOSITORY_NAME:$IMAGE_TAG .
      - docker image tag $IMAGE_REPOSITORY_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPOSITORY_NAME:$IMAGE_TAG
      - docker image tag $IMAGE_REPOSITORY_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPOSITORY_NAME:latest
  post_build:
    commands:
      - docker image push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPOSITORY_NAME:latest
      - docker image push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPOSITORY_NAME:$IMAGE_TAG
artifacts:

cache:
  paths:
    - '/root/.gradle/caches/**/*'