apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: sample-csharp-application-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: csharp-application
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csharp-application
        admission.datadoghq.com/enabled: "true"
    spec:
      containers:
        - name: csharp-application-container
          image: @ecr_container_url
          ports:
            - containerPort: 5000
          env:
            # Datadog APM用にアプリケーションがトレースを送信する先のホスト
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_ENABLED
              value: "true"
            - name: DD_ENV
              value: csharp-app
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: csharp-application-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: csharp-application